SELECT  (SUM(COALESCE(SHP.TOTAL_CHARGE_AMOUNT, 0) - COALESCE(SHP.COD_AMT, 0) - COALESCE(SHP.INTRA_CNDN_AMT, 0) - COALESCE(SHP.EXCH_aMT, 0) - COALESCE(SHP.TOT_MX_NON_REV_AMT, 0))
         -  SUM(CASE  WHEN  COALESCE(OBI.ADJ_AMT, 0)  >=  0 THEN  COALESCE(OBI.ADJ_AMT, 0) ELSE  COALESCE(OBI.DSCNT_AMT, 0) END))/23
     ,  SUM(SHP.WEIGHT)/23
  FROM  SHIPMENT_VW  SHP
        JOIN  PRA_AGREEMENT_VW  PRA
          ON  SHP.PRCNG_AGRMT_INSTC_ID  =  PRA.AGRMNT_INST_ID
        JOIN  CUSTOMER_LOCATION_VW   PRA_CUST
          ON  PRA.CUST_NBR  =  PRA_CUST.CUST_NBR
        LEFT  OUTER  JOIN  OBI_INCENTIVE_SHIPMENT_VW  OBI
          ON  SHP.SHPMT_INSTC_ID  =  OBI.SHPMT_INSTC_ID
              AND  OBI.OBI_SHPMT_STAT_CD  =  'D'
 WHERE  PRA_CUST.MAD_CODE  =  'AYMCC001900'
   AND  SHP.BILL_CLAS_CD  IN  ('A', 'C', 'D')
   AND  SHP.PICKUP_DATE  BETWEEN  '08-01-2016'  AND  '08-31-2016'
;


SELECT  (SUM(COALESCE(SHP.TOTAL_CHARGE_AMOUNT, 0) - COALESCE(SHP.COD_AMT, 0) - COALESCE(SHP.INTRA_CNDN_AMT, 0) - COALESCE(SHP.EXCH_aMT, 0) - COALESCE(SHP.TOT_MX_NON_REV_AMT, 0))
         -  SUM(CASE  WHEN  COALESCE(OBI.ADJ_AMT, 0)  >=  0 THEN  COALESCE(OBI.ADJ_AMT, 0) ELSE  COALESCE(OBI.DSCNT_AMT, 0) END))/23
     ,  SUM(SHP.WEIGHT)/23
  FROM  SHIPMENT_VW  SHP
        JOIN  PRA_AGREEMENT_VW  PRA
          ON  SHP.PRCNG_AGRMT_INSTC_ID  =  PRA.AGRMNT_INST_ID
        JOIN  CUSTOMER_LOCATION_VW   PRA_CUST
          ON  PRA.CUST_NBR  =  PRA_CUST.CUST_NBR
        LEFT  OUTER  JOIN  OBI_INCENTIVE_SHIPMENT_VW  OBI
          ON  SHP.SHPMT_INSTC_ID  =  OBI.SHPMT_INSTC_ID
              AND  OBI.OBI_SHPMT_STAT_CD  =  'D'
 WHERE  PRA_CUST.MAD_CODE  =  'AYMCC001900'
   AND  SHP.BILL_CLAS_CD  IN  ('A', 'C', 'D')
   AND  SHP.PICKUP_DATE  BETWEEN  '08-01-2017'  AND  '08-31-2017'
;




SELECT  (SUM(ACCESSORIAL_AMOUNT))/23
  FROM  ACCESSORIAL_VW  ACCS
        JOIN  SHIPMENT_VW  SHP
          ON  ACCS.SHPMT_INSTC_ID  =  SHP.SHPMT_INSTC_ID
        JOIN  ACCESSORIAL_CODE_VW   ACCS_CODE
          ON  ACCS.ACCESSORIAL_CODE_ID  =  ACCS_CODE.ACCESSORIAL_CODE_ID
        JOIN  PRA_AGREEMENT_VW  PRA
          ON  SHP.PRCNG_AGRMT_INSTC_ID  =  PRA.AGRMNT_INST_ID
        JOIN  CUSTOMER_LOCATION_VW   PRA_CUST
          ON  PRA.CUST_NBR  =  PRA_CUST.CUST_NBR
 WHERE  PRA_CUST.MAD_CODE  =  'AYMCC001900'
   AND  SHP.BILL_CLAS_CD  IN  ('A', 'C', 'D')
   AND  SHP.PICKUP_DATE  BETWEEN  '08-01-2016'  AND  '08-31-2016'
   AND  ACCS_CODE.GENERIC_ACCESSORIAL_CODE  IN  ('FSC', 'TLF')
;


SELECT  (SUM(ACCESSORIAL_AMOUNT))/23
  FROM  ACCESSORIAL_VW  ACCS
        JOIN  SHIPMENT_VW  SHP
          ON  ACCS.SHPMT_INSTC_ID  =  SHP.SHPMT_INSTC_ID
        JOIN  ACCESSORIAL_CODE_VW   ACCS_CODE
          ON  ACCS.ACCESSORIAL_CODE_ID  =  ACCS_CODE.ACCESSORIAL_CODE_ID
        JOIN  PRA_AGREEMENT_VW  PRA
          ON  SHP.PRCNG_AGRMT_INSTC_ID  =  PRA.AGRMNT_INST_ID
        JOIN  CUSTOMER_LOCATION_VW   PRA_CUST
          ON  PRA.CUST_NBR  =  PRA_CUST.CUST_NBR
 WHERE  PRA_CUST.MAD_CODE  =  'AYMCC001900'
   AND  SHP.BILL_CLAS_CD  IN  ('A', 'C', 'D')
   AND  SHP.PICKUP_DATE  BETWEEN  '08-01-2017'  AND  '08-31-2017'
   AND  ACCS_CODE.GENERIC_ACCESSORIAL_CODE  IN  ('FSC', 'TLF')
;